version: '3.8'

services:
  togetherhana:
    build: ../../Desktop
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: 111111

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"